[project]
name = "htplatform"
version = "0.0.1b"
description = "HyeTech Platform"
authors = [
    {name = "rwd-ht", email = "53872676+rwd-ht@users.noreply.github.com"},
]
dependencies = ["pydantic>=2.13.0b2"]
requires-python = ">=3.14"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project.scripts]
htp = "htp.cli:main"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.black]
line-length = 88  # this is the default

[tool.isort]
py_version = 314
profile = "black"
force_single_line = true
combine_as_imports = true
add_imports = ["from __future__ import annotations"]

[tool.pdm]
distribution = true

[tool.pdm.build]
package-dir = "src"
includes = ["src/"]


[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "coverage>=7.13.5",
]
