name: PyTest

on:
  push:
    branches:
      - dev
      - main
  # pull_request:
  #   types:
  #     - opened
  #     - synchronize
  workflow_dispatch:
jobs:
  PyTest:
    runs-on: ubuntu-latest
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      actions: write
      statuses: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        # You are now able to use PDM in your workflow
      - name: Install dependencies
        run: pdm install
      - name: Run tests
        run: pdm run coverage run -m pytest
        working-directory: .
      - id: save-coverage-html
        run: pdm run coverage html --title "Coverage for ${{ github.sha }}"
      - id: save-coverage-percentage
        run: |
          output=$(printf "%.02f" $(pdm run coverage json -q -o /dev/stdout | jq .totals.percent_covered))
          echo $output
          echo "coverage_percentage=$output" >> "$GITHUB_OUTPUT"
        working-directory: .
      - name: Add commit status
        uses: octodemo-resources/github-commit-status@v1
        with:
          context: coverage
          state: success
          description: Coverage ${{ steps.save-coverage-percentage.outputs.coverage_percentage }}%
          target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './htmlcov'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
